/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tac;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.Timer;

/**
 *
 * @author T430
 */
public class tic extends javax.swing.JFrame {
    private static int xo=0,compt=0,prog;
    private ImageIcon x = new ImageIcon(getClass().getResource("x.png"));
    private ImageIcon o = new ImageIcon(getClass().getResource("o.png"));
    private Timer treasure;
    
    
    public tic() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Tic Tac Toe");
        labelXO.setIcon(x);
        fi.hide();
        fee.hide();
        foe.hide();
        dola.show();
        treasure=new Timer(50, new GameLoading());
        treasure.start();
    }

    private class GameLoading implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent ae) {
            prog = loading.getValue();
            if(prog<100){
                prog++;
                loading.setValue(prog);
                
            }
            else{
                treasure.stop();
                foe.show();
                dola.hide();
            }
        }
        
    }
    private void setIconXO(JButton bn){
        
        if (xo==0){
            bn.setIcon(x);
        xo=1;
        compt++;
        labelXO.setIcon(o);
        bn.setEnabled(false);
        player.setText(player2.getText());
    }
    else{
        bn.setIcon(o);
        xo=0;
        compt++;
        labelXO.setIcon(x);
        bn.setEnabled(false);
        player.setText(player1.getText());
}
    }
    
    private void fi(){
        xo = 0;
        compt++;
    cast1.setIcon(null);cast1.setEnabled(true);
    cast2.setIcon(null);cast2.setEnabled(true);
    cast3.setIcon(null);cast3.setEnabled(true);
    cast5.setIcon(null);cast5.setEnabled(true);
    cast6.setIcon(null);cast6.setEnabled(true);
    cast7.setIcon(null);cast7.setEnabled(true);
    cast8.setIcon(null);cast8.setEnabled(true);
    cast9.setIcon(null);cast9.setEnabled(true);
    cast10.setIcon(null);cast10.setEnabled(true);
    labelXO.setIcon(x);
    fi.show();
    fee.hide();
    player.setText(player1.getText());
    }
    
    private void CastClick(JButton bn,JButton a1,JButton a2,JButton b1,JButton b2,JButton c1,JButton c2){
        
        if(
                bn.getIcon().equals(a1.getIcon())&& bn.getIcon().equals(a2.getIcon())||
                bn.getIcon().equals(b1.getIcon())&& bn.getIcon().equals(b2.getIcon())||
                bn.getIcon().equals(c1.getIcon())&& bn.getIcon().equals(c2.getIcon())
                ){
            
            if(bn.getIcon().equals(x)){
                game.setText(player1.getText()+"Win!");
            }
            else{
                game.setText(player2.getText()+"Win!");
            }
            fi();
        }
            EndGame();
    }
    
    private void EndGame(){
        if (compt==9){
        fi();
        game.setText("EndGame");
    }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cast4 = new javax.swing.JButton();
        fee = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cast1 = new javax.swing.JButton();
        cast2 = new javax.swing.JButton();
        cast3 = new javax.swing.JButton();
        cast5 = new javax.swing.JButton();
        cast6 = new javax.swing.JButton();
        cast7 = new javax.swing.JButton();
        cast8 = new javax.swing.JButton();
        cast9 = new javax.swing.JButton();
        cast10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelXO = new javax.swing.JLabel();
        player = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        fi = new javax.swing.JPanel();
        game = new javax.swing.JTextField();
        Replay = new javax.swing.JButton();
        Restart = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        foe = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        player1 = new javax.swing.JTextField();
        start = new javax.swing.JButton();
        p2 = new javax.swing.JLabel();
        player2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        dola = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        loading = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fee.setBackground(new java.awt.Color(153, 0, 0));
        fee.setPreferredSize(new java.awt.Dimension(400, 500));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        cast1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cast1ActionPerformed(evt);
            }
        });

        cast2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cast2ActionPerformed(evt);
            }
        });

        cast3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cast3ActionPerformed(evt);
            }
        });

        cast5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cast5ActionPerformed(evt);
            }
        });

        cast6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cast6ActionPerformed(evt);
            }
        });

        cast7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cast7ActionPerformed(evt);
            }
        });

        cast8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cast8ActionPerformed(evt);
            }
        });

        cast9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cast9ActionPerformed(evt);
            }
        });

        cast10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cast10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cast1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cast2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cast3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cast5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cast6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cast7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cast8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cast9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cast10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cast1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cast2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cast3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cast5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cast6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cast7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cast8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cast9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cast10, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tic Tac", 0, 0, new java.awt.Font("Times New Roman", 3, 24), new java.awt.Color(255, 0, 51))); // NOI18N

        player.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        player.setForeground(new java.awt.Color(255, 0, 102));
        player.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(player, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelXO, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(labelXO, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(player, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("Redo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Restart");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout feeLayout = new javax.swing.GroupLayout(fee);
        fee.setLayout(feeLayout);
        feeLayout.setHorizontalGroup(
            feeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feeLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(feeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(feeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(feeLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(feeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3)))
                    .addGroup(feeLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(19, 19, 19))
        );
        feeLayout.setVerticalGroup(
            feeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feeLayout.createSequentialGroup()
                .addGroup(feeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(feeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE))
                    .addGroup(feeLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGroup(feeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(feeLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feeLayout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );

        getContentPane().add(fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        fi.setBackground(new java.awt.Color(255, 204, 0));
        fi.setPreferredSize(new java.awt.Dimension(400, 500));

        game.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameActionPerformed(evt);
            }
        });

        Replay.setText("Replay");
        Replay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReplayActionPerformed(evt);
            }
        });

        Restart.setText("Restart");
        Restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestartActionPerformed(evt);
            }
        });

        jButton4.setText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tac/logo.png"))); // NOI18N

        javax.swing.GroupLayout fiLayout = new javax.swing.GroupLayout(fi);
        fi.setLayout(fiLayout);
        fiLayout.setHorizontalGroup(
            fiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fiLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(fiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Restart, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(game)
                    .addComponent(Replay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fiLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(49, 49, 49))
        );
        fiLayout.setVerticalGroup(
            fiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fiLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(game, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Replay, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Restart, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        getContentPane().add(fi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        foe.setBackground(new java.awt.Color(204, 0, 0));
        foe.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tac/logo.png"))); // NOI18N

        p1.setFont(new java.awt.Font("Sitka Text", 1, 30)); // NOI18N
        p1.setForeground(new java.awt.Color(0, 255, 102));
        p1.setText("Player 1:");

        player1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                player1KeyReleased(evt);
            }
        });

        start.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        start.setText("Start");
        start.setEnabled(false);
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        p2.setFont(new java.awt.Font("Sitka Text", 1, 30)); // NOI18N
        p2.setForeground(new java.awt.Color(0, 255, 102));
        p2.setText("Player 2:");

        player2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                player2KeyReleased(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setText("Close");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout foeLayout = new javax.swing.GroupLayout(foe);
        foe.setLayout(foeLayout);
        foeLayout.setHorizontalGroup(
            foeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foeLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(foeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, foeLayout.createSequentialGroup()
                        .addGroup(foeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(player1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                            .addComponent(player2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, foeLayout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))))
        );
        foeLayout.setVerticalGroup(
            foeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foeLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(player1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(player2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(foe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        dola.setBackground(new java.awt.Color(0, 0, 0));
        dola.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tac/logo.png"))); // NOI18N

        loading.setStringPainted(true);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tac/tic-tac-toe-jquery-game.jpg"))); // NOI18N

        javax.swing.GroupLayout dolaLayout = new javax.swing.GroupLayout(dola);
        dola.setLayout(dolaLayout);
        dolaLayout.setHorizontalGroup(
            dolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dolaLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(dolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dolaLayout.createSequentialGroup()
                        .addGroup(dolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(loading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dolaLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );
        dolaLayout.setVerticalGroup(
            dolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dolaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(loading, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        getContentPane().add(dola, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cast1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cast1ActionPerformed
        setIconXO(cast1);
        CastClick(cast1,cast2,cast3,cast6,cast10,cast5,cast8);
    }//GEN-LAST:event_cast1ActionPerformed

    private void cast2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cast2ActionPerformed
       setIconXO(cast2);
        CastClick(cast2,cast1,cast3,cast3,cast1,cast5,cast9);
    }//GEN-LAST:event_cast2ActionPerformed

    private void cast3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cast3ActionPerformed
        setIconXO(cast3);
        CastClick(cast3,cast2,cast1,cast6,cast8,cast7,cast10);
    }//GEN-LAST:event_cast3ActionPerformed

    private void cast5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cast5ActionPerformed
        setIconXO(cast5);
        CastClick(cast5,cast1,cast8,cast8,cast1,cast6,cast7);
    }//GEN-LAST:event_cast5ActionPerformed

    private void cast6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cast6ActionPerformed
        setIconXO(cast6);
        CastClick(cast6,cast2,cast7,cast1,cast10,cast5,cast7);
        CastClick(cast6,cast2,cast7,cast1,cast10,cast8,cast3);//important cast 7
    }//GEN-LAST:event_cast6ActionPerformed

    private void cast7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cast7ActionPerformed
        setIconXO(cast7);
        CastClick(cast7,cast3,cast10,cast5,cast6,cast10,cast3);
    }//GEN-LAST:event_cast7ActionPerformed

    private void cast8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cast8ActionPerformed
        setIconXO(cast8);
        CastClick(cast8,cast5,cast1,cast6,cast3,cast9,cast10);
    }//GEN-LAST:event_cast8ActionPerformed

    private void cast9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cast9ActionPerformed
        setIconXO(cast9);
        CastClick(cast9,cast8,cast10,cast10,cast8,cast6,cast2);
    }//GEN-LAST:event_cast9ActionPerformed

    private void cast10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cast10ActionPerformed
        setIconXO(cast10);
        CastClick(cast10,cast9,cast8,cast6,cast1,cast3,cast7);
    }//GEN-LAST:event_cast10ActionPerformed

    private void gameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gameActionPerformed

    private void ReplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReplayActionPerformed
        fi.hide();
        fee.show();
    }//GEN-LAST:event_ReplayActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        foe.hide();
        fee.show();
        player.setText(player1.getText());
    }//GEN-LAST:event_startActionPerformed

    private void player1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_player1KeyReleased
        if(player1.getText().equals("")||player1.getText().equals("")){
            start.setEnabled(false);
        }
        else{
           start.setEnabled(true); 
        }
    }//GEN-LAST:event_player1KeyReleased

    private void player2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_player2KeyReleased
        if(player1.getText().equals("")||player1.getText().equals("")){
            start.setEnabled(false);
        }
        else{
           start.setEnabled(true); 
        }
    }//GEN-LAST:event_player2KeyReleased

    private void RestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestartActionPerformed
        foe.show();
        fi.hide();
        player1.setText("");
        player2.setText("");
        start.setEnabled(false);
    }//GEN-LAST:event_RestartActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fi();
        fee.show();
        fi.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        fi();
        foe.show();
        fee.hide();
        player1.setText("");
        player2.setText("");
        start.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new tic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Replay;
    private javax.swing.JButton Restart;
    private javax.swing.JButton cast1;
    private javax.swing.JButton cast10;
    private javax.swing.JButton cast2;
    private javax.swing.JButton cast3;
    private javax.swing.JButton cast4;
    private javax.swing.JButton cast5;
    private javax.swing.JButton cast6;
    private javax.swing.JButton cast7;
    private javax.swing.JButton cast8;
    private javax.swing.JButton cast9;
    private javax.swing.JPanel dola;
    private javax.swing.JPanel fee;
    private javax.swing.JPanel fi;
    private javax.swing.JPanel foe;
    private javax.swing.JTextField game;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelXO;
    private javax.swing.JProgressBar loading;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel player;
    private javax.swing.JTextField player1;
    private javax.swing.JTextField player2;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
